baseURL = ""
languageCode = "en-us"
title = "Shazia Sultana"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "Shazia Sultana's Digital Garden on the Internet. My portfolio and blog where I write about UX/UI."
  images = ['/digital-garden-logo.png']

#[Params.newsletter]
#  title = ""
#  description = "A curated weekly digest once a week to your mailbox"
#  path = "https://www.getrevue.co/profile/username/add_subscriber"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 2
[[menu.main]]
  name = 'Projects'
  url = '/portfolio'
  weight = 3
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 4
  [[menu.main]]
  name = 'My Hobbies'
  url = '/hobbie'
  weight = 5
[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/zeenosaur'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/zeenosaur09'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/shazia-sultana-657107227/'
  weight = 3
[[menu.social]]
  name = 'Instagram'
  url = 'https://www.instagram.com/sha_zia.sul_tana/'
  weight = 4
[[menu.social]]
  name = 'Dribbble'
  url = 'https://dribbble.com'
  weight = 5
[[menu.social]]
  name = 'Email'
  url = 'mailto:kinsak.96@gmail.com'
  weight = 7



# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
